"""create_procurements_table

Revision ID: d9252adb2502
Revises: 66d8583bc846
Create Date: 2026-07-21 19:23:37.618806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9252adb2502'
down_revision: Union[str, Sequence[str], None] = '66d8583bc846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurements',
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=150), nullable=False),
    sa.Column('approved_by', sa.String(length=150), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_number')
    )
    op.create_index(op.f('ix_procurements_id'), 'procurements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurements_id'), table_name='procurements')
    op.drop_table('procurements')
    # ### end Alembic commands ###
